package sra.login.vo;

import com.cmbc.edw.model.AbstractBO;

/**
 * mapping to table [T_URM_ONLINE_REC]<br>
 * auto generated by HbmCreater.
 * 
 * @author Dunkee 2007-11-01
 */
public class OnlineRecBO extends AbstractBO {
  /** USER_ID **/
  private String userId;

  public String getUserId() {
    if (userId == null || userId.equalsIgnoreCase("NULL")) {
      return "";
    }
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  /** IS_ONLINE **/
  private String isOnline;

  public String getIsOnline() {
    if (isOnline == null || isOnline.equalsIgnoreCase("NULL")) {
      return "";
    }
    return isOnline;
  }

  public void setIsOnline(String isOnline) {
    this.isOnline = isOnline;
  }

  /** ONLINE_TIME **/
  private java.util.Date onlineTime;

  public java.util.Date getOnlineTime() {
    return onlineTime;
  }

  public void setOnlineTime(java.util.Date onlineTime) {
    this.onlineTime = onlineTime;
  }

  /** OFFLINE_TIME **/
  private java.util.Date offlineTime;

  public java.util.Date getOfflineTime() {
    return offlineTime;
  }

  public void setOfflineTime(java.util.Date offlineTime) {
    this.offlineTime = offlineTime;
  }

  public String toString() {
    return "[" + this.getClass().getName() + ":userId=" + getUserId()
        + ",isOnline=" + getIsOnline() + ",onlineTime=" + getOnlineTime()
        + ",offlineTime=" + getOfflineTime() + "]";
  }
}
